language: node_js
node_js:
- '0.10'
- '0.12'
cache:
  directories:
  - node_modules
before_install:
- npm install -g npm@3
- npm install -g semver
- npm install -g codeclimate-test-reporter
before_script:
- npm run lint
- npm run build
script:
- npm run cover
after_script:
- codeclimate-test-reporter < coverage/lcov.info
matrix:
  fast_finish: true
